create table cliente (cliente_id integer generated by default as identity, contrasena varchar(255), estado boolean, persona_id integer, primary key (cliente_id));
create table cuenta (cuenta_id integer generated by default as identity, estado boolean, num_cuenta bigint, saldo_inicial double, saldo_total double, tipo_cuenta varchar(255), cliente integer, primary key (cuenta_id));
create table movimientos (mov_id integer generated by default as identity, fecha date, saldo double, tipo_movimiento varchar(255), valor double, cuenta integer, primary key (mov_id));
create table persona (persona_id integer generated by default as identity, direccion varchar(255), edad integer, genero varchar(255), identificacion varchar(255), nombre varchar(255), telefono varchar(255), primary key (persona_id));
create table retiro (num_cuenta bigint not null, valor_diario double, primary key (num_cuenta));
alter table cliente add constraint FKmc52upywn8gona2iiwwwphb92 foreign key (persona_id) references persona;
alter table cuenta add constraint FKoro0dkes1aden3a2f0co20l69 foreign key (cliente) references cliente;
alter table movimientos add constraint FKgpwucwtokq0kuk5xbt8tl9h2m foreign key (cuenta) references cuenta;